import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero'
import { SliderData } from '@/components/SliderData'
import Slider from '@/components/slider'
import Instagram from '@/components/Instagram'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
         <Hero heading= 'Olathegreat snaps!!!' message="I enjoy taking nice shots of nature and structures"/>
         <Slider slides={SliderData}/>
         <Instagram/>
      
      
    </>
  )
}
